import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signindefault"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SigninDefault
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signintextfill"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SigninTextfill
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signupdefault"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SignupDefault
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signuptextfill"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SignupTextfill
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signupwrongemail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SignupWrongemail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/signupverification"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SignupVerification
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/dashboardone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            DashboardOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/dashboardtwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            DashboardTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/dashboardthree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            DashboardThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/calendermonth"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CalenderMonth
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/calenderdaynoevent"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CalenderDayNoevent
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/calenderday1event"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CalenderDay1Event
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/calenderweek"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CalenderWeek
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/profile"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/customer"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Customer
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/filemanagementdefault"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            FileManagementDefault
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/tracktasks"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Tracktasks
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/conversation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Conversation
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/settings"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Settings
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycscanidcard"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCScanIDCard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycscanidcardaddimage"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCScanIDCardAddimage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycscanface"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCScanFace
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycbegin"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCBegin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycintroductionstepone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCIntroductionStepOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycintroductionsteptwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCIntroductionStepTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/paymentinfo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            PaymentInfo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycconfirminformation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCConfirmInformation
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/checkout"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Checkout
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycsignature"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCSignature
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycsuccessful"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCSuccessful
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycintroductionstepthree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCIntroductionStepThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/ekycintroductionstepfour"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            EKYCIntroductionStepFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/checkoutone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CheckoutOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/shippinginfo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ShippingInfo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/shopsearch"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ShopSearch
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/shopdetailitem"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ShopDetailitem
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/shopreviews"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ShopReviews
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/cartproductlist"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CartProductList
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            href="/addproduct"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            AddProduct
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
